version: '3.5'

services: 
    banco_postgres:
        container_name: banco_de_dados_II
        image: postgres:14
        shm_size: '2gb'
        environment:
             POSTGRES_HOST_AUTH_METHOD: "trust"
        ports: 
            - 5432:5432
        volumes:
            - ./db_postgres:/var/lib/postgresql/data
            - .:/conversao